### ISSUE TITLE
Misclick leads to constant selecting

### ISSUE THREAD

**Issue by iabervon** [SudokuPad/sudokupad-web-issues#18] opened 2022-06-19 01:03 UTC
In the web app, if you put the pointer between the puzzle and the numbers, press and hold the left mouse button, move the pointer onto a number, release the button, and move the pointer to the puzzle, it starts selecting cells like you have the button held, even though you don't. This can happen by accident if you're trying to click on a number and press the button slightly before your pointer reaches the numbers. Happens for me on Firefox and Chrome, on Linux, and Simon's done it by mistake in videos a couple of times, I think.

An equivalent way to trigger it is to drag the "Sven Neumann" link (from next to "Created by") onto the "0" button, and then move the pointer across the puzzle.

**Comment by NeilGirdhar** [comment] 2023-03-01 02:25
Control-right-click on a cell seems to do this too.  Reloading the puzzle puts it in a good state again.

**Comment by killroy42** [comment] 2023-08-05 17:43
Is this still an issue? I cannot reproduce the exact issue now. But I do recall something similar occurring not too long ago. I'll close it for now, but if you still encounter this I'll re-open.

**Closed as not planned** 2023-08-05 17:44 UTC
Labels: cannot-reproduce
